easy_admin:
    disabled_actions: ['show']
    entities:
        # List the entity class name you want to manage
        Livre:
          class: App\Entity\Livre

        Auteur:
          class: App\Entity\Auteur
          form:
            fields:
              - { property: 'Nom_Complet' }
              - { property: 'date_Naissance'}
              - { property: 'date_Deces' }
              - { property: 'Biographie', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
              - { property: 'Nationalite' }
              - { property: 'livres' }

        Genre:
          class: App\Entity\Genre

        Nationalit:
          class: App\Entity\Nationalit

#        - App\Entity\User
